Repository wavesplatform/nodemon, pull requests merged in 2022-11, with the labels that each got.

#112 Added base target alert
  cmd/nodemon/nodemon.go
  pkg/analysis/analyzer.go
  pkg/analysis/analyzer_test.go
  pkg/analysis/criteria/base_target.go
  pkg/analysis/criteria/base_target_test.go
  pkg/analysis/criteria/state_hash_test.go
  pkg/analysis/finders/fork_finder_test.go
  pkg/api/api.go
  pkg/entities/alerts.go
  pkg/entities/events.go
  pkg/entities/statements.go
  pkg/scraping/client.go
  pkg/scraping/scraper.go
  pkg/storing/events/events_test.go
Labels: enhancement

#125 Bump github.com/wavesplatform/gowaves from 1ea0d7ff7a82 to 2739e7dab10f
  go.mod
  go.sum
Labels: dependencies, go

#126 Fixed deadlock in 'Scraper.poll'.
  pkg/scraping/scraper.go
Labels: bug

#124 Fixed privated nodes handling
  cmd/nodemon/nodemon.go
  go.mod
  pkg/analysis/analyzer.go
  pkg/analysis/analyzer_test.go
  pkg/api/api.go
  pkg/entities/events.go
  pkg/entities/notifications.go
  pkg/scraping/scraper.go
  pkg/storing/events/events_test.go
  pkg/storing/nodes/nodes.go
  pkg/storing/private_nodes/private_nodes.go
Labels: bug

#127 Refactor events storage methods
  pkg/analysis/criteria/state_hash.go
  pkg/storing/events/events.go
Labels: refactoring

#133 Add incomplete criterion.
  pkg/analysis/analyzer.go
  pkg/analysis/criteria/incomplete.go
  pkg/analysis/criteria/incomplete_test.go
Labels: enhancement

#136 Use 'zap' logger in HTTP API request logger middleware.
  pkg/api/api.go
Labels: enhancement

#134 Added statement at height handler
  cmd/bots/internal/common/environment.go
  cmd/bots/internal/common/messaging/handlers.go
  cmd/bots/internal/common/messaging/pair/client.go
  cmd/bots/internal/common/templates/node_statement.html
  cmd/bots/internal/common/templates/nodes_status_different_hashes.html
  cmd/bots/internal/common/templates/nodes_status_different_hashes.md
  cmd/bots/internal/common/templates/nodes_status_ok.html
  cmd/bots/internal/common/templates/nodes_status_ok.md
  cmd/bots/internal/common/templates/nodes_status_ok_short.html
  cmd/bots/internal/common/templates/nodes_status_ok_short.md
  cmd/bots/internal/telegram/handlers/handlers.go
  cmd/bots/internal/telegram/messages/base_messages.go
  cmd/bots/internal/telegram/messages/error_messages.go
  pkg/analysis/finders/fork_finder.go
  pkg/entities/node.go
  pkg/messaging/pair/request_types.go
  pkg/messaging/pair/requests.go
  pkg/messaging/pair/responses.go
  pkg/messaging/pair/server.go
  pkg/storing/events/events.go
  pkg/storing/events/events_test.go
Labels: enhancement
