Repository wavesplatform/nodemon, pull requests merged in 2023-02, with the labels that each got.

#156 Add private nodes initial state
  cmd/nodemon/nodemon.go
  pkg/api/api.go
  pkg/entities/events.go
  pkg/storing/private_nodes/private_nodes.go
Labels: enhancement

#155 Changed log data for log record inside 'alertsStorage.PutAlert'.
  pkg/analysis/alerts_storage.go
Labels: bug

#160 Bump golang.org/x/net to 0.7.0
  go.mod
  go.sum
Labels: dependencies, go

#161 Set Go version to 1.19
  .github/workflows/go.yml
  .github/workflows/security.yml
  go.mod
Labels: enhancement, wip

#162 Reduced matrix for 'lint' CI job.
  .github/workflows/go.yml
Labels: github_actions

#159 Add 'sync.RWMutex' for 'nodes.Storage' methods.
  pkg/storing/nodes/nodes.go
Labels: bug
