Repository wavesplatform/nodemon, pull requests merged in 2024-05, with the labels that each got.

#234 Bump golang from 1.21.1-alpine3.18 to 1.22.1-alpine3.19
  Dockerfile-nodemon
  Dockerfile-nodemon-discord
  Dockerfile-nodemon-telegram
Labels: dependencies, docker

#235 Bump github.com/procyon-projects/chrono from 1.1.2 to codnect.io/chrono 1.1.3
  cmd/bots/discord/discord.go
  cmd/bots/internal/common/environment.go
  cmd/bots/telegram/telegram.go
  go.mod
  go.sum
Labels: dependencies, go

#246 Fields blockID and generator made references.
  go.sum
  pkg/analysis/analyzer_test.go
  pkg/analysis/criteria/base_target_test.go
  pkg/analysis/criteria/state_hash_test.go
  pkg/analysis/finders/fork_finder_test.go
  pkg/api/api.go
  pkg/entities/events.go
  pkg/entities/statements.go
  pkg/messaging/pair/responses.go
  pkg/scraping/scraper.go
  pkg/storing/events/events_test.go
Labels: question
